// Mocks generated by Mockito 5.0.17 from annotations
// in myfinance/test/features/presentation/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myfinance/features/registration/domain/entities/profile.dart'
    as _i3;
import 'package:myfinance/features/registration/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:myfinance/features/registration/domain/usecases/get_profile_information.dart'
    as _i4;
import 'package:myfinance/features/registration/domain/usecases/initialize_application.dart'
    as _i7;
import 'package:myfinance/features/registration/domain/usecases/set_profile_information.dart'
    as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeProfileRepository_0 extends _i1.Fake
    implements _i2.ProfileRepository {}

class _FakeProfile_1 extends _i1.Fake implements _i3.Profile {}

/// A class which mocks [GetProfileInformation].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileInformation extends _i1.Mock
    implements _i4.GetProfileInformation {
  MockGetProfileInformation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get profileRepository =>
      (super.noSuchMethod(Invocation.getter(#profileRepository),
          returnValue: _FakeProfileRepository_0()) as _i2.ProfileRepository);
  @override
  _i5.Future<_i3.Profile> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue: Future<_i3.Profile>.value(_FakeProfile_1()))
          as _i5.Future<_i3.Profile>);
}

/// A class which mocks [SetProfileInformation].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetProfileInformation extends _i1.Mock
    implements _i6.SetProfileInformation {
  MockSetProfileInformation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get profileRepository =>
      (super.noSuchMethod(Invocation.getter(#profileRepository),
          returnValue: _FakeProfileRepository_0()) as _i2.ProfileRepository);
  @override
  _i5.Future<bool> execute(_i3.Profile? profile) =>
      (super.noSuchMethod(Invocation.method(#execute, [profile]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [InitializeApplication].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitializeApplication extends _i1.Mock
    implements _i7.InitializeApplication {
  MockInitializeApplication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get profileRepository =>
      (super.noSuchMethod(Invocation.getter(#profileRepository),
          returnValue: _FakeProfileRepository_0()) as _i2.ProfileRepository);
  @override
  void execute() => super.noSuchMethod(Invocation.method(#execute, []),
      returnValueForMissingStub: null);
}
